### ISSUE TITLE
Post-NU5 testnet issues

### ISSUE THREAD

**Issue by conradoplg** [adityapk00/zecwallet-lite#156]
I'm making tests of the Zebra + lightwalletd integration using ZecWallet Lite. However the results below were reproduced with `zcashd` too.

I'm using the upstream lightwalletd due to [this issue](https://github.com/adityapk00/lightwalletd/issues/11), so be aware that some (or all?) of these issues might be caused by that.

**Describe the bug**

Testnet + upstream lightwalletd results:

- Shielded Sapling transactions show up in the wallet, but never become spendable
  - Investigating `zecwallet-light-cli` code, this seems to be caused by the [`anchor_height`](https://github.com/adityapk00/zecwallet-light-cli/blob/5e73adef4615786954f97f80e6fbbcd650ee39c7/lib/src/lightclient.rs#L625) always having the wallet birthday and never increasing. Not sure why.
- When you click a transaction, it shows the wrong TXID (the old SHA256d one, instead of the NU5 TXID)
  - I can also see `getrawtransaction`s queries to Zebra using the wrong TXID (and of course, failing). But somehow the shielded transactions and balance show up correctly
- Transparent transactions / balance do not show up at all (even though [my address](https://chain.so/address/ZECTEST/tmKTZCZo23GQvB4VFwL96iFGKe6fh3wKC9d) has a balance)
  - `getaddressbalance` does not seem to be called, so it seems it computes the balance manually (I do see a `getaddresstxids` followed by a `getrawtransaction` which work successfully)
  - This seems more related to the usage of upstream lightwalletd

**To Reproduce**

Start lightwalletd from [this version](https://github.com/zcash/lightwalletd/commit/ab4c0fef70dcb195f131d3d794e0c9cec2972dba)

Run ZecWallet Lite with a hardcoded lightwalletd server (I used [this](https://github.com/ZcashFoundation/zecwallet-lite/pull/1). I also had to change [this line](https://github.com/adityapk00/zecwallet-lite/blob/a38e64419a0c4d9acab975503583c8e16b6bb480/src/components/LoadingScreen.tsx#L151) to use `"test"`)

Open ZecWallet Lite

Send a shielded transaction and a transparent transaction to your wallet.

**Expected behavior**

- It should allow you to send from your shielded balance
- It should show your transparent balance

**Desktop (please complete the following information):**

Ubuntu 20.04, ZecWallet Lite 1.7.8

**Comment by str4d** [comment]
> - When you click a transaction, it shows the wrong TXID (the old SHA256d one, instead of the NU5 TXID)

This is https://github.com/zcash/lightwalletd/issues/392, which is being addressed in https://github.com/zcash/lightwalletd/pull/393.

**Comment by conradoplg** [comment]
> > * When you click a transaction, it shows the wrong TXID (the old SHA256d one, instead of the NU5 TXID)
> 
> This is [zcash/lightwalletd#392](https://github.com/zcash/lightwalletd/issues/392), which is being addressed in [zcash/lightwalletd#393](https://github.com/zcash/lightwalletd/pull/393).

Thanks @str4d! I tested it with the fix and the problem still seems to happen. I think ZecWallet might be computing the TXID by itself somewhere, but I couldn't find it so far (I'm not too familiar with the codebase yet)

**Comment by str4d** [comment]
Did you clear both the `lightwalletd` cache, and the `zecwallet-lite` state, before testing? The former needs to happen or else the incorrect txids continue to be served (or see the latest merged PR where you can now truncate the cache to a specific height), and the latter needs to happen if `zecwallet-lite` caches the txids locally (which I would expect it does).

**Comment by conradoplg** [comment]
> Did you clear both the `lightwalletd` cache, and the `zecwallet-lite` state, before testing? The former needs to happen or else the incorrect txids continue to be served (or see the latest merged PR where you can now truncate the cache to a specific height), and the latter needs to happen if `zecwallet-lite` caches the txids locally (which I would expect it does).

@str4d thanks, that was it! I forgot about the `lightwalletd` cache. After clearing them, ZecWallet Lite is showing the correct TXID.

(It is still not allowing me to spend the shielded balance, but I guess it's a separate issue.)

**Comment by zancas** [comment]
We're working on this issue in our fork, tracking here:   https://github.com/zingolabs/zecwalletlitelib/issues/36

**Comment by daira** [comment]
This issue covers many different problems. Can the remaining ones not fixed by the lightwalletd v0.4.12 release be split into separate issues?

**Comment by AloeareV** [comment]
We've got a fix in progress here: https://github.com/zingolabs/zecwalletlitelib/pull/48

It's WIP, as the tests aren't updated yet. We're successfully parsing transactions past NU5 height on testnet, though.

**Comment by zancas** [comment]
@AloeareV 's fix now has some (but not all) tests running here:

https://github.com/zingolabs/zecwalletlitelib/pull/53

We can make a provisional `alpha` release with a button click, if we land that PR in `dev`.   I'm not sure that there'd be value to that but there may be tooling around releases that could use it.   I don't think it has a significant downside, to cut a provisional release..   except...   the above hypothetical tooling might pick up our (also hypothetical) new bugs...
